### PR TITLE
Fix form responses

### LINKED ISSUE #109: 🐞[BUG] Link to claim stacking reward tx incorrect
**Describe the bug**
The message and link of the claim stacking reward transaction show "User registered successfully" and the link is https://minecitycoins.com/mia/stacking?chain=testnet

**To Reproduce**
1. Go to 'https://minecitycoins.com/mia/stacking?chain=mainnet'
2. Click on 'Claim Rewards'
3. See error

**Screenshots**

Screenshot from 2021-11-10 22-17-54

### PR DESCRIPTION
**Pull request by whoabuddy**
Fixes #109, standardizes copy across all responses, and makes text wrap if in a small container.

### CODE REVIEW

File: src/components/activation/RegisterUser.js [hunk 1]
```diff
@@ -141,7 +141,7 @@ export default function RegisterUser(props) {
         setFormMsg({
           type: 'success',
           hidden: false,
-          text: 'User registered successfully',
+          text: 'Activation transaction successfully sent',
```
Comment (friedger) [inline src/components/activation/RegisterUser.js:144]: This should be reverted

**Review by friedger — CHANGES_REQUESTED** [review]
On change should be reverted, the rest looks good.
